application:
  subdomain: musicdl
  upstreams:
    - location: /
      backend: http://musicdl:8080/
  public_path:
    - /
services:
  musicdl:
    # guohuiyuan/go-music-dl
    # upstream: guohuiyuan/go-music-dl:1.0.32
    image: docker.1ms.run/guohuiyuan/go-music-dl:1.0.32
    user: root
    command: "./music-dl web --port 8080 --no-browser --vg-cover --vg-audio --vg-lyric --vg-export"
    environment:
      - TZ=Asia/Shanghai
    binds:
      - /lzcapp/var/data:/root/data
