package: community.lazycat.app.musicdl
version: 1.0.34
name: Music DL
description: A web-based music downloader with support for multiple platforms
min_os_version: 1.5.0
author: guohuiyuan
license: MIT
homepage: https://github.com/guohuiyuan/go-music-dl
locales:
  zh:
    name: Music DL
    description: 一个音乐搜索与下载工具
  en:
    name: Music DL
    description: Web-based music downloader supporting multiple platforms
permissions:
  required:
    - net.internet
